version: '3.4'

services:
  smartcityapp:
    build:
      image: smartcityapp
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User Id=rm552998;Password=050404;;Data Source=oracle.fiap.com.br:1521/ORCL;

