name: Docker Build and Deploy to Development

on:
  push:
    branches:
      - main  # ou qualquer outra branch que você queira disparar o deploy

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build -f Projeto.net2/Projeto.net2/Projeto.net/SmartCityApp/Dockerfile -t hellengod/smartcityapp:latest .

    - name: Push the Docker image to Docker Hub
      run: |
        docker push hellengod/smartcityapp:latest

  deploy_development:
    runs-on: ubuntu-latest
    needs: build
    environment: development
    steps:
    - name: Deploy to Development Environment
      run: |
        echo "Deploying to Development Server"
        # Adicione aqui o comando para o deploy no servidor de desenvolvimento
        # Exemplo: ssh username@dev-server "docker pull hellengod/smartcityapp:latest && docker run -d hellengod/smartcityapp:latest"

  verify_deployment_development:
    runs-on: ubuntu-latest
    needs: deploy_development
    environment: development
    steps:
    - name: Verify Deployment in Development
      run: |
        # Comando para verificar se o serviço está funcionando no servidor de desenvolvimento
        # Exemplo: curl -f http://dev-server/health || exit 1
        curl -f http://dev-server/health || exit 1
